#!/usr/bin/env python3
# (c) https://t.me/TelethonChat/37677 and SpEcHiDe
#
# Licensed under the Raphielscape Public License, Version 1.d (the "License");
# you may not use this file except in compliance with the License.
#

from telethon.sessions import StringSession
from telethon.sync import TelegramClient

print(
    """Please go-to my.telegram.org
Login using your Telegram account
Click on API Development Tools
Create a new application, by entering the required details
Check your Telegram saved messages section to copy the STRING_SESSION"""
)
API_KEY = int(input("Enter API_KEY here: "))
API_HASH = input("Enter API_HASH here:002cf61bb3081758036578d91d42bcf9 ")

with TelegramClient(StringSession(), API_KEY, API_HASH) as client:
    print("1BVtsOKEBu16vYuMnCz2kk3gDHFn5xkjMg5tN88CHr6i2nQ0_l5MpcGSu7stPMzpbXpcUbQju2JgOYBlQfTj-hu85oeoPh-1zHMQxAZxUnotj5JC1esEO0fcMX27Ar4YBz821uY3B06L6aLIkF3tqbVOQHVQ24sVAGvgaHKwO95fL9y3j8BHOxYXCPMAer0vKoIbF-SGHAsQdFJIRHsoh-OpiNjbkA2eWgRVdSPwUoyLVqNfCy21kFN1W4yEE5DutuGx5ATHPfmTvPlocYUdwhpsKWLild4FcdPRBoMSApRxOXyqmtgl0fSXt_E3K7PUCFIn71EGJcBSNpfTCaAIOoIgrpYA4cpE= ")
    session_string = client.session.save()
    saved_messages_template = """Grup Support @AyiinXdSupport

<code>STRING_SESSION</code>: <code>{}</code>

⚠️ <i>Please be careful before passing this value to third parties</i>""".format(
        session_string
    )
    client.send_message("me", saved_messages_template, parse_mode="html")
